include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - build/**
    - android/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: true
    cascade_invocations: true
    directives_ordering: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unawaited_futures: true
