name: loc
description: Free and open-source location-based reminder for Android
repository: https://github.com/AbdeltwabMF/loc
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.5.9+59

environment:
  flutter: 3.7.5
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_map: ^3.1.0
  flutter_ringtone_player: ^3.2.0
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  latlong2: ^0.8.1
  provider: ^6.0.5
  url_launcher: ^6.1.8
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  assets:
    - assets/ca/lets-encrypt-r3.pem
    - assets/images/icon.png
    - assets/images/featureGraphic.png
    - assets/images/background.jpg
  fonts:
      - family: Fantasque
        fonts:
          - asset: assets/fonts/Fantasque Sans Mono Regular Nerd Font.ttf
      - family: NotoArabic
        fonts:
          - asset: assets/fonts/NotoSansArabic-Regular.ttf
  uses-material-design: true