name: loc
description: Free and open-source location-based reminder for Android
repository: https://github.com/AbdeltwabMF/loc
homepage: https://loc.abdeltwab.xyz
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+100

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.2
  flutter_local_notifications: ^22.3.1
  geolocator: ^14.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  latlong2: ^0.10.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
