name: loc
description: Free and open-source location-based reminder for Android
publish_to: 'none'

version: 2.5.0+113

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '3.47.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_compass: ^0.8.1
  flutter_map: ^8.3.2
  flutter_local_notifications: ^22.3.1
  geolocator: ^14.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  latlong2: ^0.10.1
  package_info_plus: ^10.2.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  flutter_background_service: ^5.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  geolocator_android:
    git:
      url: https://github.com/Zverik/flutter-geolocator.git
      ref: e3991f9e63514933e96b57a8f839ad6511c4afc2
      path: geolocator_android

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
    - family: BalooBhaijaan2
      fonts:
        - asset: assets/fonts/BalooBhaijaan2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooBhaijaan2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooBhaijaan2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BalooBhaijaan2-Bold.ttf
          weight: 700
