name: loc
description: Free and open-source location-based reminder for Android
repository: https://github.com/AbdeltwabMF/loc
homepage: https://loc.abdeltwab.xyz
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+101

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_map: ^8.3.2
  flutter_local_notifications: ^22.3.1
  geolocator: ^14.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  latlong2: ^0.10.1
  package_info_plus: ^10.2.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  geolocator_android:
    git:
      url: https://github.com/Zverik/flutter-geolocator.git
      ref: floss
      path: geolocator_android

flutter:
  uses-material-design: true
