name: loc
description: A location-based reminder

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  geolocator: ^9.0.2
  flutter_ringtone_player: ^3.2.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  fonts:
      - family: Fantasque
        fonts:
          - asset: assets/fonts/Fantasque Sans Mono Regular Nerd Font.ttf
          - asset: assets/fonts/Fantasque Sans Mono Bold Nerd Font.ttf
          - asset: assets/fonts/Fantasque Sans Mono Italic Nerd Font.ttf
            style: italic
      - family: NotoArabic
        fonts:
          - asset: assets/fonts/NotoSansArabic-Regular.ttf
  assets:
    - assets/ca/

flutter_icons:
  android: launcher_icon
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/app_icon.png
  min_sdk_android: 16 # android min sdk min:16, default 21
