---

name: Release

on:
  push:
    tags:
    - 'v[0-9].[0-9].[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: flutter create --platforms=ios,android .

      - name: Build artifacts
        run: |
          build_number=$(awk -F+ '{print $2}' pubspec.yaml)
          flutter build apk --build-name=${{github.ref_name}} --build-number=$build_number --release

      - name: Release artifacts and source code
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          name: ${{github.ref_name}}
          makeLatest: true
          generateReleaseNotes: true
